---
title: "Bd Challenge Assays - Spotted Salamander and ZAP24"
author: "JUC"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

### This is the HTML copied over from Spotted Salamander 2024 folder - which has the original R-code and data set 
```{r, message=FALSE, warning=FALSE}
setwd("C:/Users/Owner/OneDrive - Smithsonian Institution/Spotted Salamander 2024/#R-files")
#setwd("/Users/Julian/Library/CloudStorage/OneDrive-SmithsonianInstitution/Spotted Salamander 2024/#R-files")

#setwd("/Users/Carly/OneDrive - Smithsonian Institution/NSF-BBSRC2022/ZooAmphibianProject/LabworkMucosomes/")
library(ggplot2)
library(ggrepel)
library(plyr)
library(dplyr)
library(tidyr)
```

### Read and manipulate data set
```{r}
inhibit_scores <- read.csv("InhibitionScoresMucosome.csv")

# calculate mean and standard error
meanInhib_2 <- ddply(inhibit_scores, .(AmphibianID, Plate, Column),
                   summarize,
                   mean = mean(final_inhibition_percent))

standard_errors <- ddply(inhibit_scores, .(AmphibianID, Plate, Column),
                         summarize,
                         stderr = sd(final_inhibition_percent) / sqrt(length(final_inhibition_percent)),
sd = sd(final_inhibition_percent))

# merge standard errors with mean inhibition data
Scores <- merge(meanInhib_2, standard_errors, by = c("AmphibianID",
                                                     "Plate", "Column"))
# subset spotted sals and ZAP data
ScoresSpot <- Scores %>% 
  filter((Plate == 2 & Column %in% c(1, 2, 3, 4, 5)) | (Plate == 1))
# also want to merge back some of the metadata
SpotMD <- read.csv("spot_md.csv")
ScoresSpot$AmphibianID <- gsub("-","", as.character(ScoresSpot$AmphibianID))
ScoresSpot$AmphibianID <- gsub("F","", as.character(ScoresSpot$AmphibianID))
Spot1 <- merge(ScoresSpot, SpotMD, by = c("AmphibianID"), all = TRUE)
Spot <- Spot1 %>% 
  filter((Spot1$sample_type %in% "individual")) %>% 
  mutate(location = recode(location, "big pool" = "Big pool", "small pool" = "Small pool")) %>% 
  filter(!(AmphibianID %in% c("WSBP19", "WSBP14","WSBP15", "WSBP23", "WSBP25", "WSBP26", "WSBP29", "WSSP01", "WSSP02", "WSSP05", "WSSP09")))
```


### Set theme
```{r}
theme_set(theme_classic() +
            theme(panel.spacing.x = unit(2, "lines")) +
            theme(axis.text.x = element_text(vjust = 0)) +
            theme(axis.title.x = element_text(vjust = -1)) +
            theme(legend.position = "bottom"))
```
*Some Colors*
```{r}
c("#1C86EE","#FFC125")
c("#7D7D7D", "#575757","#EE6363")
c("#00B2EE", "#009ACD", "#1E90FF")
```

### Create figures
#### Spotted's
```{r, warning=FALSE}
# Create the scatter plot with standard error bars
ggplot(Spot, aes(x = AmphibianID, y = mean)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 0.5)) +
  theme(axis.title = element_text(size = 20)) +
  theme(axis.text = element_text(size = 12)) +
  labs(x = "", y = "Bd Inhibition Score") +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 1.0, color = "gray") +
  geom_hline(yintercept = -46,linetype = "dashed", linewidth = 1.0, color = "#EE6363") +
    geom_errorbar(aes(ymin = mean - sd,
                    ymax = mean + sd),
                width = 0.3, size = 1, color = "#575757") +
  geom_point(size = 3.5, color = "#575757") +
  geom_point(size = 2, color = "#FFC125") +
  facet_wrap(~ location, scales = "free", ncol = 2) + 
  scale_shape_discrete(guide = "none") + 
  theme(strip.text = element_text(size = 15))
```


#### For supplemental
```{r}
SpotSup <- Spot1 %>% 
  filter(!(sample_type %in% c("environmental", "negative extraction control", "positive extraction control", "positive pcr control", "negative pcr control"))) %>% 
  filter(!(AmphibianID %in% c("WSBPNC6", "WSBPNC1", "WSSPNC1", "HK")))
                
ggplot(SpotSup, aes(x = AmphibianID, y = mean)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.2)) +
  theme(axis.title = element_text(size = 15)) +
  theme(axis.text = element_text(size = 15)) +
  labs(x = "", y = "Bd Inhibition Score") +
  geom_hline(yintercept = 0,
             linetype = "dashed",
             linewidth = 1.0, color = "gray") +
    geom_errorbar(aes(ymin = mean - sd,
                    ymax = mean + sd),
                width = 0.3, size = 1, color = "#575757") +
  geom_point(size = 4.5, color = "#575757") +
  geom_point(size = 3, color = "#FFC125") +
  facet_wrap(~ location, scales = "free", ncol = 2) + 
  scale_shape_discrete(guide = "none") + 
  theme(strip.text = element_text(face = "bold", size = 15), 
        strip.background = element_rect(fill = "#1E90FF"))


write.csv(SpotSup, "mucosomePreFilter.csv")
```

